CREATE TABLE LEAF_ALLOC (
  BIZ_TAG VARCHAR2(128 char)  NOT NULL DEFAULT '',
  MAX_ID NUMBER(20,0) NOT NULL DEFAULT '1',
  STEP NUMBER(11,0) NOT NULL,
  DESCRIPTION VARCHAR2(256 char) DEFAULT NULL,
  UPDATE_TIME TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (BIZ_TAG)
);
COMMENT ON TABLE LEAF_ALLOC IS 'LEAF分配表';
